source "https://rubygems.org"
ruby "2.1.0"

gem "cobweb", :git => "git://github.com/arturoherrero/cobweb/"
gem "foreman"
gem "resque"

group :development, :test do
  gem "guard-rspec"
  gem "rspec"
  gem "vcr"
  gem "webmock", "~> 1.15.2"  # VCR is known to work with WebMock >= 1.8.0, < 1.16
end
